package pojos;
// Generated Nov 6, 2018 10:13:30 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Barang generated by hbm2java
 */
@Entity
@Table(name="Barang"
    ,catalog="db165314102"
)
public class Barang  implements java.io.Serializable {


     private String idBarang;
     private String nama;
     private int stok;
     private double harga;

    public Barang() {
    }

    public Barang(String idBarang, String nama, int stok, double harga) {
       this.idBarang = idBarang;
       this.nama = nama;
       this.stok = stok;
       this.harga = harga;
    }
   
     @Id 

    
    @Column(name="ID_Barang", unique=true, nullable=false, length=9)
    public String getIdBarang() {
        return this.idBarang;
    }
    
    public void setIdBarang(String idBarang) {
        this.idBarang = idBarang;
    }

    
    @Column(name="nama", nullable=false, length=50)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

    
    @Column(name="stok", nullable=false)
    public int getStok() {
        return this.stok;
    }
    
    public void setStok(int stok) {
        this.stok = stok;
    }

    
    @Column(name="harga", nullable=false, precision=22, scale=0)
    public double getHarga() {
        return this.harga;
    }
    
    public void setHarga(double harga) {
        this.harga = harga;
    }




}


